import{A as d,r as u,i as p,S as f}from"./assets/vendor-D6Ij70I3.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const e of s)if(e.type==="childList")for(const c of e.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function n(s){const e={};return s.integrity&&(e.integrity=s.integrity),s.referrerPolicy&&(e.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?e.credentials="include":s.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function i(s){if(s.ep)return;s.ep=!0;const e=n(s);fetch(s.href,e)}})();(()=>{const t=document.querySelector(".js-menu"),r=document.querySelector(".js-menu"),n=document.querySelector(".js-menu-close"),i=document.querySelector(".nav-list");r.addEventListener("click",s),n.addEventListener("click",s);function s(){const e=r.getAttribute("aria-expanded")==="true"||!1;r.setAttribute("aria-expanded",!e),t.classList.toggle("is-open"),document.body.classList.toggle("is-open")}i.addEventListener("click",e=>{e.target.nodeName==="A"&&e.target.nodeName==="A"&&(t.classList.remove("is-open"),document.body.classList.remove("is-open"))})})();document.addEventListener("DOMContentLoaded",function(){const t=document.querySelectorAll("img.lazy");if("IntersectionObserver"in window){const r=new IntersectionObserver((n,i)=>{n.forEach(s=>{if(s.isIntersecting){const e=s.target;e.dataset.src&&(e.src=e.dataset.src,e.addEventListener("error",()=>{console.warn(`Failed to load image: ${e.dataset.src}`)},{once:!0}),i.unobserve(e))}})},{rootMargin:"100px"});t.forEach(n=>{r.observe(n)})}else t.forEach(r=>{r.dataset.src&&(r.src=r.dataset.src)})});new d(".accordion-container");u();const a=document.querySelector(".swiper");let o;const g=async()=>{try{const t=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!t.ok)throw new Error(`HTTP Error: ${t.status}`);return await t.json()}catch(t){return console.error("Failed to fetch reviews:",t),[]}},m=t=>`
    <li class="swiper-slide" id="slide">
        <p class="user-comment">${t.review}</p>
        <div class="user-info">
          <img class="user-photo" src="${t.avatar_url}" alt="User photo" width="40" height="40" loading="lazy"/>
          <h4 class="user-name">${t.author}</h4>
        </div>
    </li>`,w=async()=>{const t=await g();if(!t.length){a.innerHTML="<p>Not found</p>",p.error({message:"Reviews cannot be loaded at this time.",position:"bottomRight"});return}const r=t.map(n=>m(n)).join("");a.querySelector(".swiper-wrapper").innerHTML=r,o=new f(".swiper",{slidesPerView:1,spaceBetween:10,grabCursor:!0,slideToClickedSlide:!0,speed:800,keyboard:{enabled:!0},mousewheel:{enabled:!0},navigation:{nextEl:".reviews-btn-right",prevEl:".reviews-btn-left"},breakpoints:{768:{slidesPerView:1,spaceBetween:12},1280:{slidesPerView:2,spaceBetween:32}},autoplay:{delay:3e3,stopOnLastSlide:!1,disableOnInteraction:!0},pagination:{el:".swiper-pagination",clickable:!0,dynamicBullets:!0},on:{slideChange:()=>{l()}}}),l()};function l(){if(!o)return;const t=document.querySelector(".reviews-btn-right"),r=document.querySelector(".reviews-btn-left");t.disabled=o.isEnd,r.disabled=o.isBeginning;const n=document.querySelector(".js-btn-left"),i=document.querySelector(".js-btn-right");n.style.transition="none",i.style.transition="none",o.isEnd&&(i.style.stroke="#e4e5e6",n.style.stroke="#292929"),o.isBeginning&&(n.style.stroke="#e4e5e6",i.style.stroke="#292929"),!o.isEnd&&!o.isBeginning&&(n.style.stroke="#292929",i.style.stroke="#292929"),t.classList.toggle("disabled",o.isEnd),r.classList.toggle("disabled",o.isBeginning)}w();
//# sourceMappingURL=index.js.map
